// angular-proj/src/app/add.shoe.to.shop/add.shoe.to.shop.component.ts
import { Component } from '@angular/core';
import { FormsModule } from "@angular/forms";
import { Router, ActivatedRoute } from "@angular/router";
import CatalogShoes from "../entities/catalog.shoes"
import { ShopService } from '../services/shop.service';
import { ShoeService } from '../services/shoe.service';
import { NgFor } from '@angular/common';
import Shop from '../entities/shop';
import Shoe from '../entities/shoe';

@Component({
  selector: 'app-add.shoe.to.shop',
  standalone: true,
  imports: [FormsModule, NgFor],
  templateUrl: './add.shoe.to.shop.component.html',
  styleUrl: './add.shoe.to.shop.component.css'
})
export class AddShoeToShopComponent {
  shop: Shop = new Shop();
  shoes: Shoe[] = [];
  catalogShoe: CatalogShoes = new CatalogShoes();
  id: number;

  constructor(private shopService: ShopService, 
              private shoeService: ShoeService,
              private router: Router, 
              private activateRoute: ActivatedRoute) {
    this.id = activateRoute.snapshot.params["id"];
  }

  async ngOnInit(){
    this.shop = await this.shopService.getShopById(this.id);
    this.shoes = await this.shoeService.getShoes();
    console.log(this.shop)
  }

  async addShoeToShop() {
    await this.shopService.addShoeToShop(this.shop.id, this.catalogShoe.shoeId);
    this.router.navigate(["/shops"]);
  }
}

<section class="form-container-shoes">
    <h2>Shoes</h2>
    
    <table class="table table-striped table-hover">   
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Title
                </th>
                <th>
                    Price
                </th>
                <th>
                    Description
                </th>
                <th>
                    Manufacturer
                </th>
                <th>
                    Brand
                </th>
                <th>
                    Size
                </th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let shoe of shoes">
                <td>
                    {{shoe.id}}
                </td>
                <td>
                    {{shoe.title}}
                </td>
                <td>
                    {{shoe.price}}
                </td>
                <td>
                    {{shoe.description}}
                </td>
                <td>
                    {{shoe.manufacturer}}
                </td>
                <td>
                    {{shoe.brand}}
                </td>
                <td>
                    {{shoe.size}}
                </td>
            </tr>
        </tbody>
    </table> 

    <section class="form-container">
        <input
            placeholder="ShoeId"
            class="form-control"
            type="number"
            [(ngModel)]="catalogShoe.shoeId"
        />
        <button
            class="btn btn-info"
            (click)="addShoeToShop()">
            Add
        </button>
    </section>

</section>

// react-proj/src/routes/addShoeToShop.js
import React, { useState, useEffect } from 'react';
import { getBaskShopById, addShoeToShop } from "../api/shopService"
import { getBaskShoe } from "../api/shoeService"
import { useLoaderData, useNavigate } from "react-router-dom";
import "./shops.css"

export async function loader({ params }) {
    const shop = await getBaskShopById(params.shopId);
    return { shop };
}

export default function AddShoeToShop() {
    const navigate = useNavigate();

    const { shop } = useLoaderData();
    const [shoes, setShoes] = useState([]);
    const [shoeId, setShoeId] = useState();

    useEffect(() => {
        loadShoes()
    }, []);

    return (
        <section className="form-container-shoes">
            <h2>Shoes</h2>
            
            <table className="table table-striped table-hover">   
                <thead>
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            Title
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Manufacturer
                        </th>
                        <th>
                            Brand
                        </th>
                        <th>
                            Size
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {shoes.map(shoe =>
                        <tr key={shoe.id}>
                            <td>
                                {shoe.id}
                            </td>
                            <td>
                                {shoe.title}
                            </td>
                            <td>
                                {shoe.price}
                            </td>
                            <td>
                                {shoe.description}
                            </td>
                            <td>
                                {shoe.manufacturer}
                            </td>
                            <td>
                                {shoe.brand}
                            </td>
                            <td>
                                {shoe.size}
                            </td>
                        </tr>
                    )}
                </tbody>
            </table> 

            <section className="form-container">
                <input
                    placeholder="ShoeId"
                    className="form-control"
                    type="number"
                    onChange={(e) => setShoeId(e.target.value)}
                />
                <button
                    className="btn btn-info"
                    onClick={addShoeToShopClick}>
                    Add
                </button>
            </section>
        </section>
    );

    async function loadShoes() {
        const shoes = await getBaskShoe()
        setShoes(shoes)
    }

    async function addShoeToShopClick() {
        await addShoeToShop(shop.id, shoeId)
        navigate('/shops')
    }
}
