// angular-proj/src/app/get.shoes.by.shop/get.shoes.by.shop.component.ts
import { Component } from '@angular/core';
import { FormsModule } from "@angular/forms";
import { Router, ActivatedRoute } from "@angular/router";
import { ShopService } from '../services/shop.service';
import { ShoeService } from '../services/shoe.service';
import { NgFor } from '@angular/common';
import Shop from '../entities/shop';
import Shoe from '../entities/shoe';

@Component({
  selector: 'app-get.shoes.by.shop',
  standalone: true,
  imports: [FormsModule, NgFor],
  templateUrl: './get.shoes.by.shop.component.html',
  styleUrl: './get.shoes.by.shop.component.css'
})
export class GetShoeByShopComponent {
  shop: Shop = new Shop();
  shoes: Shoe[] = [];
  id: number;

  constructor(private shopService: ShopService, 
              private shoeService: ShoeService,
              private router: Router, 
              private activateRoute: ActivatedRoute) {
    this.id = activateRoute.snapshot.params["id"];
  }

  async ngOnInit(){
    this.shop = await this.shopService.getShopById(this.id);
    await this.getShoeByShop();
  }

  async getShoeByShop() {
    this.shoes = await this.shoeService.getShoesByShopId(this.shop.id);
  }
}

<section class="form-container-shoes">
    <h2>Shoes</h2>
    
    <table class="table table-striped table-hover">   
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Title
                </th>
                <th>
                    Price
                </th>
                <th>
                    Description
                </th>
                <th>
                    Manufacturer
                </th>
                <th>
                    Brand
                </th>
                <th>
                    Size
                </th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let shoe of shoes">
                <td>
                    {{shoe.id}}
                </td>
                <td>
                    {{shoe.title}}
                </td>
                <td>
                    {{shoe.price}}
                </td>
                <td>
                    {{shoe.description}}
                </td>
                <td>
                    {{shoe.manufacturer}}
                </td>
                <td>
                    {{shoe.brand}}
                </td>
                <td>
                    {{shoe.size}}
                </td>
            </tr>
        </tbody>
    </table> 

</section>

// react-proj/src/routes/getShoesByShop.js
import React, { useState } from 'react';
import { getBaskShopById } from "../api/shopService"
import { getShoesByShopId } from "../api/shoeService"
import { useLoaderData } from "react-router-dom";
import "./shops.css"

export async function loader({ params }) {
    const shop = await getBaskShopById(params.shopId);
    return { shop };
}


export default function GetShoesByShop() {

    const { shop } = useLoaderData();
    const [shoes, setShoes] = useState([]);
  
    loadShoes()

    return (
        <section class="form-container-shoes">

            <h2>Shoes</h2>
            
            <table className="table table-striped table-hover">   
                <thead>
                    <tr>
                        <th>
                            Id
                        </th>
                        <th>
                            Title
                        </th>
                        <th>
                            Price
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            Manufacturer
                        </th>
                        <th>
                            Brand
                        </th>
                        <th>
                            Size
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {shoes.map(shoe =>
                        <tr key={shoe.id}>
                            <td>
                                {shoe.id}
                            </td>
                            <td>
                                {shoe.title}
                            </td>
                            <td>
                                {shoe.price}
                            </td>
                            <td>
                                {shoe.description}
                            </td>
                            <td>
                                {shoe.manufacturer}
                            </td>
                            <td>
                                {shoe.brand}
                            </td>
                            <td>
                                {shoe.size}
                            </td>
                        </tr>
                    )}
                </tbody>
            </table> 

        </section>
    );

    async function loadShoes() {
        const shoes = await getShoesByShopId(shop.id)
        setShoes(shoes)
    }

}
