// react-proj/src/routes/profile.js
import { useContext, useEffect, useState } from "react";
import { AppContext } from "../contexts/contexts";
import { useNavigate } from "react-router-dom";
import { removeUserById, updateUser } from "../api/userService";

export default function Profile() {
    const appContext = useContext(AppContext);

    const navigate = useNavigate();
    
    const [login, setLogin] = useState(appContext.user.login);
    const [email, setEmail] = useState(appContext.user.email);
    const [password, setPassword] = useState(appContext.user.password);
    const [roleId, setRoleId] = useState(appContext.user.roleId);

    useEffect(() => {
        setLogin(appContext.user.login);
        setEmail(appContext,user.email);
        setPassword(appContext,user.password);
        setRoleId(appContext,user.roleId);
    }, [])

    return (
        <section className="profile-container">
            <div className="profile-card">
                <input
                    placeholder='Логин'
                    value={login}
                    onChange={e => setLogin(e.target.value)}
                />
                <input
                    placeholder='Email'
                    value={email}
                    onChange={e => setEmail(e.target.value)}
                />
                <input
                    placeholder='Пароль'
                    value={password}
                    onChange={e => setPassword(e.target.value)}
                />
                <input
                    placeholder='Роль'
                    value={roleId}
                    onChange={e => setRoleId(e.target.value)}
                />
                <button
                    className="background-color-green"
                    onClick={updateUserButtonOnClick}
                >
                    Редактировать
                </button>
                <button
                    className="background-color-gray"
                    onClick={logoutButtonOnClick}
                >
                    Выйти
                </button>
                <button
                    className="background-color-red"
                    onClick={removeUserButtonOnClick}
                >
                    Удалить аккаунт
                </button>
            </div>
        </section>
    );

    async function updateUserButtonOnClick() {
        await updateUser(appContext.user.id, login, email, password, roleId);
        const user = JSON.parse(JSON.stringify(appContext.user));
        user.login = login;
        user.email = email;
        user.password = password;
        user.roleId = roleId;
        appContext.setUser(user);
    }

    async function logoutButtonOnClick() {
        appContext.removeCookie('userId');
        appContext.removeCookie('token');
        appContext.setIsAuthenticated(false);
        navigate('/');
    }

    async function removeUserButtonOnClick() {
        await removeUserById(appContext.user.id);
        logoutButtonOnClick();
    }
}

// angular-proj/src/app/profile/profile.component.ts
import { Component } from '@angular/core';
import { AuthorizationService } from '../services/authorization.service';
import { FormsModule } from '@angular/forms';
import { UserService } from '../services/user.service';
import User from '../entities/user';

@Component({
  selector: 'app-profile',
  standalone: true,
  imports: [FormsModule],
  templateUrl: './profile.component.html',
  styleUrl: './profile.component.css'
})
export class ProfileComponent {
  login = '';
  email = '';
  password = '';
  user = new User;
  
  constructor(private authorizationService: AuthorizationService,
    private userService: UserService) {
    authorizationService.user.subscribe(user => {
      this.user = user;
      this.login = user.login;
      this.email = user.email;
      this.password = user.password;
    });
  }

  logOut() {
    this.authorizationService.logOut();
    window.location.href = '/signin';
  }

  async removeUser() {
    await this.userService.removeUserById(this.user.id);
    this.logOut();
  }
}
<section
    class="profile-container"
>
    <div
        class="profile-card"
    >
        <input
            placeholder='Login'
            [(ngModel)]="login"
        />
        <input
            placeholder='Email'
            [(ngModel)]="email"
        />
        <input
            placeholder='Password'
            [(ngModel)]="password"
        />
        <button
            class="background-color-gray"
            (click)="logOut()"
        >
            Выйти
        </button>
        <button
            class="background-color-red"
            (click)="removeUser()"
        >
            Удалить аккаунт
        </button>
    </div>
</section>
